load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# My repository!
local_repository(
    name = "bzlmodrio-studica",
    path = "../",
)

########################
# Download Dependencies
########################
http_archive(
    name = "rules_cc",
    sha256 = "0d3b4f984c4c2e1acfd1378e0148d35caf2ef1d9eb95b688f8e19ce0c41bdf5b",
    strip_prefix = "rules_cc-0.1.4",
    url = "https://github.com/bazelbuild/rules_cc/releases/download/0.1.4/rules_cc-0.1.4.tar.gz",
)

http_archive(
    name = "rules_java",
    sha256 = "1558508fc6c348d7f99477bd21681e5746936f15f0436b5f4233e30832a590f9",
    url = "https://github.com/bazelbuild/rules_java/releases/download/8.12.0/rules_java-8.12.0.tar.gz",
)

http_archive(
    name = "rules_jvm_external",
    sha256 = "c18a69d784bcd851be95897ca0eca0b57dc86bb02e62402f15736df44160eb02",
    strip_prefix = "rules_jvm_external-6.3",
    url = "https://github.com/bazelbuild/rules_jvm_external/releases/download/6.3/rules_jvm_external-6.3.tar.gz",
)

http_archive(
    name = "rules_bazelrio",
    sha256 = "0c5a98476ac5b606689863b7b9ef3f7d685c47ce2681e448ca977e8e95de31c1",
    url = "https://github.com/bzlmodRio/rules_bazelrio/releases/download/0.0.14/rules_bazelrio-0.0.14.tar.gz",
)

http_archive(
    name = "rules_bzlmodrio_toolchains",
    sha256 = "b86f16f282a767bf73a341efcbd955613e4a20aa6f1fe7f229583af68e51acf8",
    url = "https://github.com/wpilibsuite/rules_bzlmodRio_toolchains/releases/download/2025-1.bcr5/rules_bzlmodRio_toolchains-2025-1.bcr5.tar.gz",
)

# TODO replace with released version once they make one that has Austins patch
http_archive(
    name = "bzlmodrio-allwpilib",
    sha256 = "8c36b55cef9ce00bdf2124fda4bafc0ed7ec662064119a0daad721018c4dac25",
    strip_prefix = "bzlmodRio-allwpilib-b56c6a9dd55181c24a6a5b93b1e565d29da36cc3",
    url = "https://github.com/bzlmodRio/bzlmodRio-allwpilib/archive/b56c6a9dd55181c24a6a5b93b1e565d29da36cc3.tar.gz",
)

http_archive(
    name = "bzlmodrio-opencv",
    sha256 = "27dff7aaedd00165b1a94867616ebf383220532e3956892cec649197077a9d01",
    url = "https://github.com/bzlmodRio/bzlmodRio-opencv/releases/download/2025.4.10.0-3.bcr3/bzlmodRio-opencv-2025.4.10.0-3.bcr3.tar.gz",
)

http_archive(
    name = "bzlmodrio-ni",
    sha256 = "5ee1e2d6c1a670eba178eaa5c933f31dccf550b7ab613d4b22c37ead45497c45",
    url = "https://github.com/bzlmodRio/bzlmodRio-ni/releases/download/2025.2.0.bcr1/bzlmodRio-ni-2025.2.0.bcr1.tar.gz",
)

http_archive(
    name = "googletest",
    sha256 = "8ad598c73ad796e0d8280b082cebd82a630d73e73cd3c70057938a6501bba5d7",
    strip_prefix = "googletest-1.14.0",
    urls = ["https://github.com/google/googletest/archive/refs/tags/v1.14.0.tar.gz"],
)

http_archive(
    name = "bazel_features",
    sha256 = "a015f3f2ebf4f1ac3f4ca8ea371610acb63e1903514fa8725272d381948d2747",
    strip_prefix = "bazel_features-1.31.0",
    url = "https://github.com/bazel-contrib/bazel_features/releases/download/v1.31.0/bazel_features-v1.31.0.tar.gz",
)

http_archive(
    name = "bazel_skylib",
    sha256 = "51b5105a760b353773f904d2bbc5e664d0987fbaf22265164de65d43e910d8ac",
    url = "https://github.com/bazelbuild/bazel-skylib/releases/download/1.8.1/bazel-skylib-1.8.1.tar.gz",
)

http_archive(
    name = "rules_pmd",
    sha256 = "676aea680376c32dfaab2293962f95f7755c14183833b3cd8f62323f43b7cf75",
    url = "https://github.com/bzlmodRio/rules_pmd/releases/download/7.2.0.bcr1/rules_pmd-7.2.0.bcr1.tar.gz",
)

http_archive(
    name = "rules_checkstyle",
    sha256 = "7bfc1e0d587a30da4c6f0865fe8a8f2c5dfeaa188a3dd7047a4b9d0ba7192e4c",
    url = "https://github.com/bzlmodRio/rules_checkstyle/releases/download/10.12.2.bcr1/rules_checkstyle-10.12.2.bcr1.tar.gz",
)

http_archive(
    name = "rules_wpiformat",
    sha256 = "d27a5706aff034c84fca018f46c751575792a2ef267cb5a9af70c677b2b52c40",
    url = "https://github.com/bzlmodRio/rules_wpiformat/releases/download/2025.33/rules_wpiformat-2025.33.tar.gz",
)

http_archive(
    name = "rules_spotless",
    sha256 = "edb9b9768a44c23110b446624dcfd6717302cec51e5cad0b9156690d169bc8d5",
    url = "https://github.com/bzlmodRio/rules_spotless/releases/download/2.40.0.bcr1/rules_spotless-2.40.0.bcr1.tar.gz",
)

# TODO replace with released version once they make one that has Austins patch
http_archive(
    name = "rules_python",
    sha256 = "731e3a5ed4fb1270909a8dc077902a58ea7c741ea44c6ad75662820b08da771c",
    strip_prefix = "rules_python-29a7f6a0d5c8996f4d3f36e08269e0faf478927b",
    url = "https://github.com/bazel-contrib/rules_python/archive/29a7f6a0d5c8996f4d3f36e08269e0faf478927b.tar.gz",
)

http_archive(
    name = "rules_proto",
    sha256 = "0e5c64a2599a6e26c6a03d6162242d231ecc0de219534c38cb4402171def21e8",
    strip_prefix = "rules_proto-7.0.2",
    url = "https://github.com/bazelbuild/rules_proto/archive/refs/tags/7.0.2.tar.gz",
)

http_archive(
    name = "com_google_protobuf",
    sha256 = "10a0d58f39a1a909e95e00e8ba0b5b1dc64d02997f741151953a2b3659f6e78c",
    strip_prefix = "protobuf-29.0",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/v29.0.tar.gz"],
)

########################

########################
# Setup Dependencies
########################
load("@bazel_features//:deps.bzl", "bazel_features_deps")

bazel_features_deps()

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

load("@rules_java//java:rules_java_deps.bzl", "rules_java_dependencies")

rules_java_dependencies()

load("@rules_java//java:repositories.bzl", "rules_java_toolchains")

rules_java_toolchains()

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()

load("@bzlmodrio-studica//private/non_bzlmod_dependencies:setup_dependencies.bzl", "get_java_dependenicies", "setup_dependencies")

setup_dependencies()

load("@rules_shell//shell:repositories.bzl", "rules_shell_dependencies", "rules_shell_toolchains")

rules_shell_dependencies()

rules_shell_toolchains()
########################

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_artifacts, maven_repositories = get_java_dependenicies()

# Add junit
maven_artifacts += [
    "org.junit.jupiter:junit-jupiter-api:5.10.1",
    "org.junit.jupiter:junit-jupiter-params:5.10.1",
    "org.junit.jupiter:junit-jupiter-engine:5.10.1",
    "org.junit.platform:junit-platform-commons:1.6.1",
    "org.junit.platform:junit-platform-console:1.6.1",
    "org.junit.platform:junit-platform-engine:1.6.1",
    "org.junit.platform:junit-platform-launcher:1.6.1",
    "org.junit.platform:junit-platform-suite-api:1.6.1",
]

maven_install(
    name = "maven",
    artifacts = maven_artifacts,
    repositories = maven_repositories,
    # maven_install_json = "//build_scripts/bazel/deps:maven_install.json",
)

#####################
# Styleguide
#####################
http_archive(
    name = "rules_wpi_styleguide",
    sha256 = "6f8b428bf07319c26ea1187d868fc2538c29fafccad7717e0043411b0cd6466f",
    url = "https://github.com/bzlmodRio/rules_wpi_styleguide/releases/download/2025.06.22/rules_wpi_styleguide-2025.06.22.tar.gz",
)

load("@rules_checkstyle//dependencies:load_dependencies.bzl", "load_checkstyle_dependencies")
load("@rules_pmd//dependencies:load_dependencies.bzl", "load_pmd_dependencies")
load("@rules_spotless//dependencies:load_dependencies.bzl", "load_spotless_dependencies")
load("@rules_wpiformat//dependencies:load_dependencies.bzl", "load_wpiformat_dependencies")

load_checkstyle_dependencies()

load_pmd_dependencies()

load_wpiformat_dependencies()

load_spotless_dependencies()

load("@rules_checkstyle_dependencies//:defs.bzl", checkstyle_pinned_maven_install = "pinned_maven_install")
load("@rules_pmd_dependencies//:defs.bzl", pmd_pinned_maven_install = "pinned_maven_install")
load("@rules_spotless_dependencies//:defs.bzl", spotless_pinned_maven_install = "pinned_maven_install")
load("@rules_wpiformat_pip//:requirements.bzl", "install_deps")

install_deps()

pmd_pinned_maven_install()

checkstyle_pinned_maven_install()

spotless_pinned_maven_install()
#####################

http_archive(
    name = "rules_bzlmodrio_jdk",
    integrity = "sha256-OrJI8gl3PiEw3J54p/jtNydjMY2xRlpI1yfKfPKnIYQ=",
    strip_prefix = "rules_bzlmodrio_jdk-23a1c1fd1a9e1d1521164c854be10e3eb35e84cd",
    urls = ["https://github.com/wpilibsuite/rules_bzlmodRio_jdk/archive/23a1c1fd1a9e1d1521164c854be10e3eb35e84cd.tar.gz"],
)

load("@rules_bzlmodrio_jdk//:maven_deps.bzl", "setup_legacy_setup_jdk_dependencies")

setup_legacy_setup_jdk_dependencies()
